# Generated by Django 4.0.6 on 2022-08-06 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_desc',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='email',
            field=models.EmailField(default='NULL', max_length=264),
        ),
        migrations.AddField(
            model_name='course',
            name='mobile',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
